In [1]:
import numpy as np 
import pandas as pd

In [12]:
arr = np.array([[1,2,3],[1,2,3],])

In [7]:
arr[:2,1:]

array([[2, 3],
       [2, 3]])

In [15]:
pd.DataFrame(arr).shape

(2, 3)

In [10]:
a =(1,2)

In [11]:
a[1]= 3

TypeError: 'tuple' object does not support item assignment

In [18]:
df = pd.read_csv('FoodBalanceSheets_E_Africa_NOFLAG.csv', encoding='utf-8')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf4 in position 87447: invalid continuation byte

In [19]:
df = pd.read_clipboard()

In [20]:
df

Area Code      Area  Item Code           Item  Element Code  \
0              4   Algeria       2501     Population           511   
1              4   Algeria       2501     Population          5301   
2              4   Algeria       2901    Grand Total           664   
3              4   Algeria       2901    Grand Total           674   
4              4   Algeria       2901    Grand Total           684   
...          ...       ...        ...            ...           ...   
60938        181  Zimbabwe       2899  Miscellaneous          5142   
60939        181  Zimbabwe       2899  Miscellaneous           645   
60940        181  Zimbabwe       2899  Miscellaneous           664   
60941        181  Zimbabwe       2899  Miscellaneous           674   
60942        181  Zimbabwe       2899  Miscellaneous           684   

                                      Element             Unit     Y2014  \
0               Total Population - Both sexes     1000 persons  38924.00   
1                    Domestic supply quantity      1000 tonnes      0.00   
2               Food supply (kcal/capita/day)  kcal/capita/day   3377.00   
3      Protein supply quantity (g/capita/day)     g/capita/day     94.90   
4          Fat supply quantity (g/capita/day)     g/capita/day     80.06   
...                                       ...              ...       ...   
60938                                    Food      1000 tonnes     42.00   
60939     Food supply quantity (kg/capita/yr)               kg      3.06   
60940           Food supply (kcal/capita/day)  kcal/capita/day      3.00   
60941  Protein supply quantity (g/capita/day)     g/capita/day      0.10   
60942      Fat supply quantity (g/capita/day)     g/capita/day      0.04   

          Y2015     Y2016     Y2017     Y2018  
0      39728.00  40551.00  41389.00  42228.00  
1          0.00      0.00      0.00      0.00  
2       3379.00   3372.00   3341.00   3322.00  
3         94.35     94.72     92.82     91.83  
4         79.36     77.40     80.19     77.28  
...         ...       ...       ...       ...  
60938     46.00     33.00     19.00     16.00  
60939      3.33      2.35      1.33      1.08  
60940      4.00      3.00      1.00      1.00  
60941      0.11      0.08      0.04      0.04  
60942      0.05      0.03      0.02      0.01  

[60943 rows x 12 columns]

In [22]:
df.describe()

Area Code     Item Code  Element Code          Y2014          Y2015  \
count  60943.000000  60943.000000  60943.000000   59354.000000   59395.000000   
mean     134.265576   2687.176706   3814.856456     134.196282     135.235966   
std       72.605709    146.055739   2212.007033    1567.663696    1603.403984   
min        4.000000   2501.000000    511.000000   -1796.000000   -3161.000000   
25%       74.000000   2562.000000    684.000000       0.000000       0.000000   
50%      136.000000   2630.000000   5142.000000       0.090000       0.080000   
75%      195.000000   2775.000000   5511.000000       8.340000       8.460000   
max      276.000000   2961.000000   5911.000000  176405.000000  181137.000000   

               Y2016          Y2017          Y2018  
count   59408.000000   59437.000000   59507.000000  
mean      136.555222     140.917765     143.758381  
std      1640.007194    1671.862359    1710.782658  
min     -3225.000000   -1582.000000   -3396.000000  
25%         0.000000       0.000000       0.000000  
50%         0.080000       0.100000       0.070000  
75%         8.430000       9.000000       9.000000  
max    185960.000000  190873.000000  195875.000000

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60943 entries, 0 to 60942
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Area Code     60943 non-null  int64  
 1   Area          60943 non-null  object 
 2   Item Code     60943 non-null  int64  
 3   Item          60943 non-null  object 
 4   Element Code  60943 non-null  int64  
 5   Element       60943 non-null  object 
 6   Unit          60943 non-null  object 
 7   Y2014         59354 non-null  float64
 8   Y2015         59395 non-null  float64
 9   Y2016         59408 non-null  float64
 10  Y2017         59437 non-null  float64
 11  Y2018         59507 non-null  float64
dtypes: float64(5), int64(3), object(4)
memory usage: 5.6+ MB


In [30]:
df['Y2015'].std()

1603.4039839425013

In [44]:
def corrCheck(df, main, cklst):
    a = []
    for i in cklst:
        a.append((df[main].corr(df[i]),i))
    print(sorted(a)[-1])

In [45]:
corrCheck(df, 'Element Code', ['Y2014','Y2015','Y2016','Y2017','Y2018'])

(0.024456819495221736, 'Y2014')


In [49]:
df['Y2016'].isnull().sum()/len(df['Y2016'])

0.025187470259094565

In [65]:
df.groupby(['Y2014','Element'],).sum()

Area Code  Item Code  Element Code  \
Y2014     Element                                                             
-1796.0   Stock Variation                      159       2657          5072   
-1631.0   Stock Variation                      159       2924          5072   
-849.0    Residuals                            266       5444         10340   
-838.0    Stock Variation                      184       2907          5072   
-685.0    Stock Variation                      143       2905          5072   
...                                            ...        ...           ...   
 90425.0  Total Population - Both sexes         59       2501           511   
 98094.0  Total Population - Both sexes        238       2501           511   
 108756.0 Domestic supply quantity             159       2907          5301   
 109593.0 Production                           159       2907          5511   
 176405.0 Total Population - Both sexes        159       2501           511   

                                            Y2015     Y2016     Y2017  \
Y2014     Element                                                       
-1796.0   Stock Variation                   -73.0     -12.0       0.0   
-1631.0   Stock Variation                     6.0     -77.0    -689.0   
-849.0    Residuals                       -1118.0   -1119.0   -1200.0   
-838.0    Stock Variation                  -827.0    -679.0    -538.0   
-685.0    Stock Variation                  3418.0   -3225.0     689.0   
...                                           ...       ...       ...   
 90425.0  Total Population - Both sexes   92443.0   94447.0   96443.0   
 98094.0  Total Population - Both sexes  100835.0  103603.0  106400.0   
 108756.0 Domestic supply quantity       110798.0  116483.0  112625.0   
 109593.0 Production                     111663.0  119330.0  117702.0   
 176405.0 Total Population - Both sexes  181137.0  185960.0  190873.0   

                                            Y2018  
Y2014     Element                                  
-1796.0   Stock Variation                     0.0  
-1631.0   Stock Variation                     5.0  
-849.0    Residuals                       -1196.0  
-838.0    Stock Variation                  -567.0  
-685.0    Stock Variation                   399.0  
...                                           ...  
 90425.0  Total Population - Both sexes   98424.0  
 98094.0  Total Population - Both sexes  109224.0  
 108756.0 Domestic supply quantity       117038.0  
 109593.0 Production                     118172.0  
 176405.0 Total Population - Both sexes  195875.0  

[9095 rows x 7 columns]

In [55]:
df.columns

Index(['Area Code', 'Area', 'Item Code', 'Item', 'Element Code', 'Element',
       'Unit', 'Y2014', 'Y2015', 'Y2016', 'Y2017', 'Y2018'],
      dtype='object')

In [59]:
df

Area Code      Area  Item Code           Item  Element Code  \
0              4   Algeria       2501     Population           511   
1              4   Algeria       2501     Population          5301   
2              4   Algeria       2901    Grand Total           664   
3              4   Algeria       2901    Grand Total           674   
4              4   Algeria       2901    Grand Total           684   
...          ...       ...        ...            ...           ...   
60938        181  Zimbabwe       2899  Miscellaneous          5142   
60939        181  Zimbabwe       2899  Miscellaneous           645   
60940        181  Zimbabwe       2899  Miscellaneous           664   
60941        181  Zimbabwe       2899  Miscellaneous           674   
60942        181  Zimbabwe       2899  Miscellaneous           684   

                                      Element             Unit     Y2014  \
0               Total Population - Both sexes     1000 persons  38924.00   
1                    Domestic supply quantity      1000 tonnes      0.00   
2               Food supply (kcal/capita/day)  kcal/capita/day   3377.00   
3      Protein supply quantity (g/capita/day)     g/capita/day     94.90   
4          Fat supply quantity (g/capita/day)     g/capita/day     80.06   
...                                       ...              ...       ...   
60938                                    Food      1000 tonnes     42.00   
60939     Food supply quantity (kg/capita/yr)               kg      3.06   
60940           Food supply (kcal/capita/day)  kcal/capita/day      3.00   
60941  Protein supply quantity (g/capita/day)     g/capita/day      0.10   
60942      Fat supply quantity (g/capita/day)     g/capita/day      0.04   

          Y2015     Y2016     Y2017     Y2018  
0      39728.00  40551.00  41389.00  42228.00  
1          0.00      0.00      0.00      0.00  
2       3379.00   3372.00   3341.00   3322.00  
3         94.35     94.72     92.82     91.83  
4         79.36     77.40     80.19     77.28  
...         ...       ...       ...       ...  
60938     46.00     33.00     19.00     16.00  
60939      3.33      2.35      1.33      1.08  
60940      4.00      3.00      1.00      1.00  
60941      0.11      0.08      0.04      0.04  
60942      0.05      0.03      0.02      0.01  

[60943 rows x 12 columns]

In [64]:
df['Y2014'].loc

In [67]:
len(df['Area'].unique())

49

In [99]:
dfpract = df[['Element','Area','Y2018','Y2014','Y2015','Y2016']]

In [85]:
sorted(dfpract.groupby(by='Element').sum().values)

[array([90.]),
 array([10258.69]),
 array([11833.56]),
 array([20577.91]),
 array([25263.14]),
 array([34864.]),
 array([49056.85]),
 array([91300.97]),
 array([163902.]),
 array([181594.8]),
 array([233489.68]),
 array([287997.09]),
 array([308429.]),
 array([455261.]),
 array([1140605.]),
 array([1303841.28]),
 array([2075072.89]),
 array([2161192.1])]

In [110]:
dfpract.groupby(by=['Area','Element']).sum()['Y2018'].head(10)

Area     Element                            
Algeria  Domestic supply quantity               90023.42
         Export Quantity                          811.54
         Fat supply quantity (g/capita/day)       309.09
         Feed                                   10668.00
         Food                                   63736.33
         Food supply (kcal/capita/day)          13288.00
         Food supply quantity (kg/capita/yr)     1509.28
         Import Quantity                        36238.29
         Losses                                  7708.00
         Other uses (non-food)                   3970.08
Name: Y2018, dtype: float64